services:
  app:
    build:
      context: ./src/Web/ClientApp
      args:
        - REACT_APP_API_BASE_URL=http://localhost:8080
    image: activity-manager-web
    ports:
      - 3000:3000
    
  api:
    image: activity-manager-api
    build:
      context: .
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=activity;Username=postgres;Password=activity"
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 8080:8080

  migrations:
    image: activity-manager-migrations
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./efbundle"]
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=activity;Username=postgres;Password=activity"
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
        - db
  db:
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_DB=activity
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=activity
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
